"""add_stage_types_and_lookup_dicts

Revision ID: 08a753c4bd91
Revises: c9d2e4f6a8b1
Create Date: 2026-05-12 14:18:42.137176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08a753c4bd91'
down_revision: Union[str, None] = 'c9d2e4f6a8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_stage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contract_stage_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contracts', 'lifecycle_id',
               existing_type=sa.INTEGER(),
               comment='生命周期模板ID',
               existing_nullable=True)
    op.alter_column('contracts', 'lifecycle_stage_id',
               existing_type=sa.INTEGER(),
               comment='当前阶段ID',
               existing_nullable=True)
    op.drop_index('ix_contracts_supplier_id', table_name='contracts')
    op.drop_constraint('fk_contracts_supplier_id', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'suppliers', ['supplier_id'], ['id'])
    op.alter_column('lifecycle_stages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lifecycle_stages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lifecycle_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lifecycle_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('suppliers', sa.Column('dc_bank_name', sa.String(length=256), nullable=True, comment='数字人民币开户行'))
    op.add_column('suppliers', sa.Column('dc_bank_account', sa.String(length=64), nullable=True, comment='数字人民币账号'))
    op.drop_index('ix_suppliers_user_id', table_name='suppliers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_suppliers_user_id', 'suppliers', ['user_id'], unique=False)
    op.drop_column('suppliers', 'dc_bank_account')
    op.drop_column('suppliers', 'dc_bank_name')
    op.alter_column('lifecycle_templates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lifecycle_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lifecycle_stages', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lifecycle_stages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('fk_contracts_supplier_id', 'contracts', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_contracts_supplier_id', 'contracts', ['supplier_id'], unique=False)
    op.alter_column('contracts', 'lifecycle_stage_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当前阶段ID',
               existing_nullable=True)
    op.alter_column('contracts', 'lifecycle_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='生命周期模板ID',
               existing_nullable=True)
    op.alter_column('contract_stage_logs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contract_stage_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
