"""sync_all_models

Revision ID: 3c3f78f2c683
Revises: 5f55b2b699e1
Create Date: 2026-05-11 11:57:15.443332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3f78f2c683'
down_revision: Union[str, None] = '5f55b2b699e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='密级名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='密级代码'),
    sa.Column('level', sa.Integer(), nullable=False, comment='密级等级 1-5'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('color', sa.String(length=16), nullable=True, comment='显示颜色'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fonds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='全宗名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='全宗代码'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False, comment='bank/cash/credit/investment/other'),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('archives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('archive_no', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('fonds_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('file_no', sa.String(length=100), nullable=True),
    sa.Column('volume_no', sa.String(length=100), nullable=True),
    sa.Column('responsible_person', sa.String(length=100), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('retention_period', sa.String(length=50), nullable=True),
    sa.Column('security_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archives_archive_no'), 'archives', ['archive_no'], unique=True)
    op.create_index(op.f('ix_archives_user_id'), 'archives', ['user_id'], unique=False)
    op.create_table('body_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True, comment='体重(kg)'),
    sa.Column('height', sa.Float(), nullable=True, comment='身高(cm)'),
    sa.Column('bmi', sa.Float(), nullable=True, comment='BMI'),
    sa.Column('body_fat', sa.Float(), nullable=True, comment='体脂率(%)'),
    sa.Column('waist', sa.Float(), nullable=True, comment='腰围(cm)'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_metrics_record_date'), 'body_metrics', ['record_date'], unique=False)
    op.create_index(op.f('ix_body_metrics_user_id'), 'body_metrics', ['user_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('douban_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('box_no', sa.String(length=50), nullable=False),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_boxes_cabinet_id'), 'boxes', ['cabinet_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='预算名称'),
    sa.Column('amount', sa.Float(), nullable=False, comment='预算金额'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='预算分类'),
    sa.Column('period', sa.String(length=16), nullable=False, comment='周期: monthly/weekly/yearly'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分类名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='分类代码'),
    sa.Column('fonds_id', sa.Integer(), nullable=False, comment='所属全宗ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fonds_id'], ['fonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_fonds_code', 'categories', ['fonds_id', 'code'], unique=False)
    op.create_index(op.f('ix_categories_fonds_id'), 'categories', ['fonds_id'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('dispatch_data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='database/api/file/manual'),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/inactive/error'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_data_sources_user_id'), 'dispatch_data_sources', ['user_id'], unique=False)
    op.create_table('exercise_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(length=128), nullable=False, comment='运动名称'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='时长(分钟)'),
    sa.Column('calories_burned', sa.Float(), nullable=False, comment='消耗热量(千卡)'),
    sa.Column('exercise_type', sa.String(length=32), nullable=False, comment='运动类型'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('intensity', sa.String(length=16), nullable=False, comment='强度: low/medium/high'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_records_record_date'), 'exercise_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_exercise_records_user_id'), 'exercise_records', ['user_id'], unique=False)
    op.create_table('food_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_name', sa.String(length=128), nullable=False, comment='食物名称'),
    sa.Column('calories', sa.Float(), nullable=False, comment='热量(千卡)'),
    sa.Column('protein', sa.Float(), nullable=False, comment='蛋白质(克)'),
    sa.Column('carbs', sa.Float(), nullable=False, comment='碳水化合物(克)'),
    sa.Column('fat', sa.Float(), nullable=False, comment='脂肪(克)'),
    sa.Column('meal_type', sa.String(length=16), nullable=False, comment='餐别: breakfast/lunch/dinner/snack'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期'),
    sa.Column('serving_size', sa.String(length=32), nullable=False, comment='份量'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_records_record_date'), 'food_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_food_records_user_id'), 'food_records', ['user_id'], unique=False)
    op.create_table('knowledge_conversations',
    sa.Column('id', sa.UUID(), nullable=False, comment='对话ID'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='对话标题'),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='完整对话记录（JSON）'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kc_user_id', 'knowledge_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_conversations_user_id'), 'knowledge_conversations', ['user_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='文档ID'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='文档标题'),
    sa.Column('file_type', sa.String(length=32), nullable=False, comment='文件类型: pdf/docx/txt/md/网页'),
    sa.Column('file_path', sa.String(length=1024), nullable=True, comment='文件/导入路径'),
    sa.Column('content', sa.Text(), nullable=True, comment='原文内容'),
    sa.Column('source_url', sa.String(length=2048), nullable=True, comment='原始URL（网页导入时使用）'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: processing/ready/error'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='分块数量'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('tags', sa.String(length=1024), nullable=True, comment='标签（JSON数组字符串）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kd_status', 'knowledge_documents', ['status'], unique=False)
    op.create_index('ix_kd_user_file_type', 'knowledge_documents', ['user_id', 'file_type'], unique=False)
    op.create_index('ix_kd_user_status', 'knowledge_documents', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_user_id'), 'knowledge_documents', ['user_id'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('tmdb_url', sa.String(length=1024), nullable=True),
    sa.Column('douban_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('watch_date', sa.Date(), nullable=True),
    sa.Column('my_review', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_user_id'), 'movies', ['user_id'], unique=False)
    op.create_table('appraisal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_type', sa.String(length=20), nullable=False),
    sa.Column('appraisal_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('appraiser', sa.String(length=100), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisal_records_archive_id'), 'appraisal_records', ['archive_id'], unique=False)
    op.create_table('archive_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_files_archive_id'), 'archive_files', ['archive_id'], unique=False)
    op.create_table('borrow_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('borrower', sa.String(length=100), nullable=False),
    sa.Column('borrow_date', sa.Date(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('approver', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_records_archive_id'), 'borrow_records', ['archive_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('contract_no', sa.String(length=64), nullable=False, comment='合同编号'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='合同标题'),
    sa.Column('fonds_id', sa.Integer(), nullable=False, comment='所属全宗ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='所属分类ID'),
    sa.Column('classification_id', sa.Integer(), nullable=False, comment='密级ID'),
    sa.Column('party_a', sa.String(length=256), nullable=False, comment='甲方'),
    sa.Column('party_b', sa.String(length=256), nullable=False, comment='乙方'),
    sa.Column('amount', sa.Float(), nullable=False, comment='合同金额'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='币种'),
    sa.Column('sign_date', sa.Date(), nullable=True, comment='签订日期'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: draft/signed/in_progress/completed/terminated'),
    sa.Column('contract_type', sa.String(length=32), nullable=False, comment='合同类型: purchase/service/lease/loan/other'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('keywords', sa.String(length=512), nullable=True, comment='关键词'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fonds_id'], ['fonds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_index(op.f('ix_contracts_category_id'), 'contracts', ['category_id'], unique=False)
    op.create_index(op.f('ix_contracts_fonds_id'), 'contracts', ['fonds_id'], unique=False)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_index('ix_contracts_user_status', 'contracts', ['user_id', 'status'], unique=False)
    op.create_index('ix_contracts_user_type', 'contracts', ['user_id', 'contract_type'], unique=False)
    op.create_table('dispatch_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False, comment='crontab 表达式'),
    sa.Column('target_table', sa.String(length=200), nullable=False),
    sa.Column('query_sql', sa.Text(), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/running/success/failed'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['dispatch_data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_tasks_data_source_id'), 'dispatch_tasks', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_dispatch_tasks_next_run_at'), 'dispatch_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_dispatch_tasks_user_id'), 'dispatch_tasks', ['user_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='物品名称'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='物品分类'),
    sa.Column('price', sa.Float(), nullable=True, comment='预估价格'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('priority', sa.String(length=16), nullable=False, comment='优先级: low/medium/high'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: pending/purchased/cancelled'),
    sa.Column('store', sa.String(length=128), nullable=True, comment='购买商家'),
    sa.Column('url', sa.Text(), nullable=True, comment='商品链接'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('budget_id', sa.Integer(), nullable=True, comment='关联预算ID'),
    sa.Column('created_date', sa.Date(), nullable=True, comment='创建日期'),
    sa.Column('purchased_date', sa.Date(), nullable=True, comment='购买日期'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_items_user_id'), 'shopping_items', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False, comment='income/expense/transfer'),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False, comment='food/transport/shopping/entertainment/housing/health/education/investment/salary/other'),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('dispatch_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success/failed'),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['dispatch_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_logs_task_id'), 'dispatch_logs', ['task_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='所属合同ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='里程碑名称'),
    sa.Column('amount', sa.Float(), nullable=False, comment='里程碑金额'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='计划日期'),
    sa.Column('completed_date', sa.Date(), nullable=True, comment='完成日期'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: pending/completed/overdue'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_contract_id'), 'milestones', ['contract_id'], unique=False)
    op.create_index('ix_milestones_contract_status', 'milestones', ['contract_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_milestones_contract_status', table_name='milestones')
    op.drop_index(op.f('ix_milestones_contract_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_dispatch_logs_task_id'), table_name='dispatch_logs')
    op.drop_table('dispatch_logs')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_shopping_items_user_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_dispatch_tasks_user_id'), table_name='dispatch_tasks')
    op.drop_index(op.f('ix_dispatch_tasks_next_run_at'), table_name='dispatch_tasks')
    op.drop_index(op.f('ix_dispatch_tasks_data_source_id'), table_name='dispatch_tasks')
    op.drop_table('dispatch_tasks')
    op.drop_index('ix_contracts_user_type', table_name='contracts')
    op.drop_index('ix_contracts_user_status', table_name='contracts')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_fonds_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_category_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_borrow_records_archive_id'), table_name='borrow_records')
    op.drop_table('borrow_records')
    op.drop_index(op.f('ix_archive_files_archive_id'), table_name='archive_files')
    op.drop_table('archive_files')
    op.drop_index(op.f('ix_appraisal_records_archive_id'), table_name='appraisal_records')
    op.drop_table('appraisal_records')
    op.drop_index(op.f('ix_movies_user_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_knowledge_documents_user_id'), table_name='knowledge_documents')
    op.drop_index('ix_kd_user_status', table_name='knowledge_documents')
    op.drop_index('ix_kd_user_file_type', table_name='knowledge_documents')
    op.drop_index('ix_kd_status', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_conversations_user_id'), table_name='knowledge_conversations')
    op.drop_index('ix_kc_user_id', table_name='knowledge_conversations')
    op.drop_table('knowledge_conversations')
    op.drop_index(op.f('ix_food_records_user_id'), table_name='food_records')
    op.drop_index(op.f('ix_food_records_record_date'), table_name='food_records')
    op.drop_table('food_records')
    op.drop_index(op.f('ix_exercise_records_user_id'), table_name='exercise_records')
    op.drop_index(op.f('ix_exercise_records_record_date'), table_name='exercise_records')
    op.drop_table('exercise_records')
    op.drop_index(op.f('ix_dispatch_data_sources_user_id'), table_name='dispatch_data_sources')
    op.drop_table('dispatch_data_sources')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_fonds_id'), table_name='categories')
    op.drop_index('ix_categories_fonds_code', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_boxes_cabinet_id'), table_name='boxes')
    op.drop_table('boxes')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_body_metrics_user_id'), table_name='body_metrics')
    op.drop_index(op.f('ix_body_metrics_record_date'), table_name='body_metrics')
    op.drop_table('body_metrics')
    op.drop_index(op.f('ix_archives_user_id'), table_name='archives')
    op.drop_index(op.f('ix_archives_archive_no'), table_name='archives')
    op.drop_table('archives')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('fonds')
    op.drop_table('classifications')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
