"""add project tables

Revision ID: 5f55b2b699e1
Revises: 
Create Date: 2026-05-09 12:11:09.489926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f55b2b699e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='显示名称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False, comment='项目ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='项目状态: active/completed/archived'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='结束日期'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_created', 'projects', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_table('project_columns',
    sa.Column('id', sa.UUID(), nullable=False, comment='列ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目ID'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='列标题'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pc_project_order', 'project_columns', ['project_id', 'order'], unique=False)
    op.create_index(op.f('ix_project_columns_project_id'), 'project_columns', ['project_id'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.UUID(), nullable=False, comment='里程碑ID'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='所属项目ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='里程碑标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='里程碑描述'),
    sa.Column('due_date', sa.DateTime(), nullable=True, comment='截止日期'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: pending/in_progress/completed'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度百分比 0-100'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pm_project_due', 'project_milestones', ['project_id', 'due_date'], unique=False)
    op.create_index('ix_pm_project_status', 'project_milestones', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_project_milestones_project_id'), 'project_milestones', ['project_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='任务ID'),
    sa.Column('column_id', sa.UUID(), nullable=False, comment='所属列ID'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('assignee', sa.String(length=128), nullable=True, comment='负责人'),
    sa.Column('priority', sa.String(length=16), nullable=False, comment='优先级: low/medium/high/urgent'),
    sa.Column('due_date', sa.DateTime(), nullable=True, comment='截止日期'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='开始日期'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('tags', sa.String(length=1024), nullable=True, comment='标签（JSON数组字符串）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['project_columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_tasks_column_id'), 'project_tasks', ['column_id'], unique=False)
    op.create_index('ix_pt_column_order', 'project_tasks', ['column_id', 'order'], unique=False)
    op.create_index('ix_pt_column_priority', 'project_tasks', ['column_id', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pt_column_priority', table_name='project_tasks')
    op.drop_index('ix_pt_column_order', table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_column_id'), table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_project_milestones_project_id'), table_name='project_milestones')
    op.drop_index('ix_pm_project_status', table_name='project_milestones')
    op.drop_index('ix_pm_project_due', table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index(op.f('ix_project_columns_project_id'), table_name='project_columns')
    op.drop_index('ix_pc_project_order', table_name='project_columns')
    op.drop_table('project_columns')
    op.drop_index('ix_projects_user_status', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('ix_projects_user_created', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
