"""add timeline templates and nodes

Revision ID: eb0a562d435f
Revises: d7e8f9a0b1c2
Create Date: 2026-05-14 04:29:07.061206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0a562d435f'
down_revision: Union[str, None] = 'd7e8f9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='模板名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='所属模板ID'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='节点名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('date_source', sa.String(length=64), nullable=True, comment='日期来源: sign_date/start_date/end_date/created_at/custom'),
    sa.Column('active_statuses', sa.JSON(), nullable=True, comment='此节点在哪些合同状态下视为已达成'),
    sa.Column('icon_type', sa.String(length=32), nullable=False, comment='图标类型'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必选'),
    sa.Column('description', sa.Text(), nullable=True, comment='节点说明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['timeline_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_nodes_template_id'), 'timeline_nodes', ['template_id'], unique=False)
    op.create_index('ix_timeline_nodes_template_order', 'timeline_nodes', ['template_id', 'sort_order'], unique=False)
    op.create_table('contract_timeline_custom_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='所属合同ID'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='节点名称'),
    sa.Column('date_value', sa.Date(), nullable=True, comment='节点日期'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('icon_type', sa.String(length=32), nullable=False, comment='图标类型'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_timeline_custom_nodes_contract_id'), 'contract_timeline_custom_nodes', ['contract_id'], unique=False)
    op.create_index('ix_ctcn_contract_order', 'contract_timeline_custom_nodes', ['contract_id', 'sort_order'], unique=False)
    op.add_column('contracts', sa.Column('timeline_template_id', sa.Integer(), nullable=True, comment='时间轴模板ID'))
    op.alter_column('contracts', 'contract_type',
               existing_type=sa.VARCHAR(length=32),
               comment='合同类型: purchase/service/lease/loan/other (deprecated → contract_type_id)',
               existing_comment='合同类型: purchase/service/lease/loan/other',
               existing_nullable=False)
    op.alter_column('contracts', 'contract_type_id',
               existing_type=sa.INTEGER(),
               comment='合同类型ID (FK → contract_types)',
               existing_comment='合同类型ID (FK → contract_types.id)',
               existing_nullable=True)
    op.create_index(op.f('ix_contracts_timeline_template_id'), 'contracts', ['timeline_template_id'], unique=False)
    op.execute('ALTER TABLE contracts DROP CONSTRAINT IF EXISTS contracts_supplier_id_fkey')
    op.create_foreign_key(None, 'contracts', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contracts', 'timeline_templates', ['timeline_template_id'], ['id'], ondelete='SET NULL')
    op.alter_column('suppliers', 'id',
               existing_type=sa.UUID(),
               comment='供应商ID',
               existing_nullable=False)
    op.alter_column('suppliers', 'user_id',
               existing_type=sa.UUID(),
               comment='用户ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('suppliers', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='供应商ID',
               existing_nullable=False)
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_supplier_id_fkey', 'contracts', 'suppliers', ['supplier_id'], ['id'])
    op.drop_index(op.f('ix_contracts_timeline_template_id'), table_name='contracts')
    op.alter_column('contracts', 'contract_type_id',
               existing_type=sa.INTEGER(),
               comment='合同类型ID (FK → contract_types.id)',
               existing_comment='合同类型ID (FK → contract_types)',
               existing_nullable=True)
    op.alter_column('contracts', 'contract_type',
               existing_type=sa.VARCHAR(length=32),
               comment='合同类型: purchase/service/lease/loan/other',
               existing_comment='合同类型: purchase/service/lease/loan/other (deprecated → contract_type_id)',
               existing_nullable=False)
    op.drop_column('contracts', 'timeline_template_id')
    op.drop_index('ix_ctcn_contract_order', table_name='contract_timeline_custom_nodes')
    op.drop_index(op.f('ix_contract_timeline_custom_nodes_contract_id'), table_name='contract_timeline_custom_nodes')
    op.drop_table('contract_timeline_custom_nodes')
    op.drop_index('ix_timeline_nodes_template_order', table_name='timeline_nodes')
    op.drop_index(op.f('ix_timeline_nodes_template_id'), table_name='timeline_nodes')
    op.drop_table('timeline_nodes')
    op.drop_table('timeline_templates')
    # ### end Alembic commands ###
