"""add_stage_type_and_lookup_dict_tables

Revision ID: edc54ec647a3
Revises: 08a753c4bd91
Create Date: 2026-05-12 14:27:48.466051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc54ec647a3'
down_revision: Union[str, None] = '08a753c4bd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
